# Generated by Django 4.0.3 on 2022-04-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_estado')),
                ('uf', models.CharField(max_length=255, verbose_name='uf_estado')),
                ('nome', models.CharField(max_length=255, verbose_name='nome_estado')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_cidade')),
                ('nome', models.CharField(max_length=255, verbose_name='nome_cidade')),
                ('id_uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
