# Generated by Django 4.0.3 on 2022-04-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_estado_nome_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='nome_uf',
        ),
        migrations.AddField(
            model_name='cidade',
            name='nome_uf',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
